### ISSUE TITLE
Complete milestone feature

### ISSUE THREAD

**Issue by ttrentham** [ttrentham/ginit#54]
It currently errors out as the following

```
TypeError: graphql is not a function
    at Object.getGqlInstance (/Users/timtrentham/source/ttrentham/ginit/lib/github.js:10:34)
    at Object.getMilestoneIssues (/Users/timtrentham/source/ttrentham/ginit/lib/repo.js:34:32)
    at run (/Users/timtrentham/source/ttrentham/ginit/index.js:83:33)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by ttrentham** [comment]
Got past this with [this change](https://github.com/ttrentham/ginit/commit/c5078a88544dba7245dcc62338f48e2127824210) but now seeing an `undefined` error that will require debugging to track down.

**Comment by ttrentham** [comment]
Works now but should probably validate the repo name and the milestone

**Comment by ttrentham** [comment]
Don't have to validate the name. It's already good. Closing this out.
